services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Manuxi\SuluIconPickerBundle\Pool\BootstrapIconsPool: ~

    Manuxi\SuluIconPickerBundle\Pool\IconPoolRegistry:
        arguments:
            $pools: !tagged_iterator sulu_icon_picker.pool
        public: true

    sulu_icon_picker.pool_registry:
        alias: Manuxi\SuluIconPickerBundle\Pool\IconPoolRegistry
        public: true

    Manuxi\SuluIconPickerBundle\Admin\IconPickerAdmin:
        arguments:
            $packages: '@assets.packages'
        tags:
            - { name: 'sulu.admin' }

    Manuxi\SuluIconPickerBundle\Content\Type\IconSelectionPropertyResolver:
        tags:
            - { name: 'sulu_content.property_resolver' }

    Manuxi\SuluIconPickerBundle\Twig\IconPickerTwigExtension:
        arguments:
            $packages: '@assets.packages'
            $debug: '%kernel.debug%'
        tags:
            - { name: 'twig.extension' }
