services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Manuxi\SuluIconPickerBundle\Icon\IconSetResolver:
        arguments:
            $iconSets: '%sulu_admin.icon_sets%'
            $iconProviders: !tagged_iterator { tag: 'sulu_admin.icon_provider', index_by: 'type' }

    Manuxi\SuluIconPickerBundle\Admin\IconPickerAdmin:
        tags:
            - { name: 'sulu.admin' }

    Manuxi\SuluIconPickerBundle\Content\Type\IconSelectionPropertyResolver:
        tags:
            - { name: 'sulu_content.property_resolver' }

    Manuxi\SuluIconPickerBundle\Twig\IconPickerTwigExtension:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: 'twig.extension' }
